/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sew9.worttrainer.lriffer;
import java.io.IOException;
import java.util.*;
import javax.swing.*;
import java.net.*;

/**
 * Klasse mit der Main Methode
 * @author Lili Riffer
 * @version 04-10-2023
 */
public class App {

    public static void main(String[] args) {
         //Worteintrag
         WortEintrag we1 = new WortEintrag("Hund", "https://assets.elanco.com/8e0bf1c2-1ae4-001f-9257-f2be3c683fb1/7ae66d97-8aaa-43c2-a9a9-8a0ede30a1be/labrador_retriever_liegt_bei_sonnenschein_im_park.jpg");
         WortEintrag we2 = new WortEintrag("Haus", "https://www.snoozeproject.de/files/uploads/2021/12/Traumdeutung-Haus.jpg");
         WortEintrag we3 = new WortEintrag("Apfel", "https://images.eatsmarter.de/sites/default/files/styles/576x432/public/apfel-576x432.jpg");
 
         //Wortliste
         WortListe wl1 = new WortListe();
         wl1.addWort(we1);
         wl1.addWort(we2);
         wl1.addWort(we3);
 
         //Worttrainer
         WortTrainer wt = new WortTrainer(wl1);
         SpeichernLaden sl = new SpeichernLaden(wt);
         try {
             sl.laden();
         } catch (IOException e) {
             System.out.println("Laden fehlgeschlagen");
         }
 
         String antwort = "", versuchDavor = "Erster Versuch";
         ImageIcon ii;
 
         Random r = new Random();
         boolean  wortRichtig = false, spielBeendet = false;
 
         while(!spielBeendet) {
             WortEintrag neuesWort = wt.getWortListe().getEintragArray()[r.nextInt(wt.getWortListe().getEintragArray().length)];
             do{
                 try {
                     ii = new ImageIcon(new URL(neuesWort.getUrl()));
                     JOptionPane.showMessageDialog(null, wt.getRight()+"/"+wt.getWrong()+" Richtig erraten\nVersuch davor: "+versuchDavor+"\nMerk dir das Bild: ", "Display Image", JOptionPane.INFORMATION_MESSAGE, ii);
                     antwort = JOptionPane.showInputDialog(null, "Was war auf dem Bild zu sehen?");
                 } catch (Exception e) {
                     System.out.println("Fehler beim Bild anzeigen");
                 }
                 if(antwort.equals("")){
                     try {
                         sl.speichern();
                     } catch (IOException e) {
                         System.out.println("Fehler beim speichern");
                     }
                     spielBeendet = true;
                     break;
                 }
                 if(antwort.equals(neuesWort.getWort())) {
                     JOptionPane.showMessageDialog(null, "Richtig :)");
                     wt.addRight(1);
                     wortRichtig = true;
                     versuchDavor = "Richtig";
                 } else {
                     JOptionPane.showMessageDialog(null, "Falsch :(");
                     wt.addWrong(1);
                     wortRichtig = false;
                     versuchDavor = "Falsch";
                 }
             }while(!wortRichtig);
         }
         JOptionPane.showMessageDialog(null, wt.getFehlerQuote());
     }
}

