/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sew9.worttrainer.lriffer;
import java.io.IOException;

import javax.swing.JOptionPane;
/**
 * Klasse mit der Main Methode
 * @author Lili Riffer
 * @version 04-10-2023
 */
public class App {

    public static void main(String[] args) {
        String url ="https://elearning.tgm.ac.at";
		WortListe l = new WortListe();
		WortEintrag e = new WortEintrag("Elearning", url);
		WortEintrag ei = new WortEintrag("Hund", "https://img.welt.de");
		WortEintrag e1 = new WortEintrag("elearning", url);
		WortEintrag ei1 = new WortEintrag("Hase", "https://img.welt.de");
		WortEintrag e2 = new WortEintrag("hallo", url);
		WortEintrag ei2 = new WortEintrag("Katze", "https://img.welt.de");
		l.addWort(e);
		l.addWort(ei);
		l.addWort(e1);
		l.addWort(ei1);
		l.addWort(e2);
		l.addWort(ei2);
		if(e.checkURL(url)==false) {
            JOptionPane.showMessageDialog(null, "URL ist nicht sinnvoll", "ERROR", JOptionPane.ERROR_MESSAGE);
		}else {
			JOptionPane.showInputDialog(null, e.toString());
		}
		WortTrainer t = new WortTrainer(l);
		boolean a = l.WortDelete("vlt");
		boolean b = t.check("hund");
		boolean c = t.checkIgnoreCase("ELEarNinG");
		int versuch = Integer.parseInt(JOptionPane.showInputDialog(null, "Wie viele Versuche soll man haben?"));
		int richtig = 0;
		SpeichernLaden sl = new SpeichernLaden(l, versuch, richtig);
		sl.update(versuch, richtig);
		try {
            sl.speichern();
        } catch (IOException e3) {
            JOptionPane.showMessageDialog(null, e3.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
		System.out.println("WortListe, GesuchtesWort: "+l.findEintrag(0)+"\nKonnt ich das wort \"vlt\" löschen? "+a+"\nWorttrainer; zufälliges Wort: "+t.zufallsWort()+"\nAktuelles Wort: "+t.aktuellWort()+"\nIst dieses Wort in der Liste? "+b+"\nDasselbe, es ignoriert aber die groß/kleinschreibung: "+c );
	}
}

