/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sew9.worttrainer.lriffer;
import javax.swing.JOptionPane;

public class App {

    public static void main(String[] args) {
        JOptionPane.showMessageDialog(null, "Hallo");
    }
}
